2018-11-02 16:58:21,648 [INFO] [iris.local_web_server] Serving HTTP on 127.0.0.1 port 2000.
2018-11-02 16:58:54,157 [INFO] [mozdownload.scraper] Retrieving list of candidate builds from https://archive.mozilla.org/pub/firefox/candidates/64.0b6-candidates/
2018-11-02 16:58:54,216 [INFO] [mozdownload.scraper] Found 1 build: build1
2018-11-02 16:58:54,217 [INFO] [mozdownload.scraper] Selected build: build1
2018-11-02 16:58:54,279 [INFO] [mozdownload.scraper] File has already been downloaded: C:\Users\paul.silaghi\.iris\cache\firefox-64.0b6-build1.en-US.win64.exe
2018-11-02 16:58:59,430 [INFO] [mozdownload.scraper] Retrieving list of candidate builds from https://archive.mozilla.org/pub/firefox/candidates/64.0b6-candidates/
2018-11-02 16:58:59,486 [INFO] [mozdownload.scraper] Found 1 build: build1
2018-11-02 16:58:59,487 [INFO] [mozdownload.scraper] Selected build: build1
2018-11-02 16:58:59,540 [INFO] [iris.__main__] Latest available version for beta channel is: 64.0b6
2018-11-02 16:58:59,657 [INFO] [iris.test_runner] Running tests
2018-11-02 16:58:59,660 [INFO] [iris.test_runner] 
------------------------------------------------------------------------------------------------------------------------
2018-11-02 16:58:59,667 [INFO] [iris.test_runner] Executing: 1 - [empty]: This is an empty test case that does nothing
2018-11-02 16:59:15,059 [SUCCESS] [iris.api.helpers.results] Step: test, outcome: >>> PASSED <<<
2018-11-02 16:59:15,062 [WARNING] [iris.api.helpers.results] Step: test, outcome: >>> FAILED <<< 

------------------------------------------------------------------------------------------------------------------------
» Traceback (most recent call last):                                                                                   «
»   File "C:\Users\paul.silaghi\.virtualenvs\iris-DBojdd3p\Scripts\iris-script.py", line 11, in <module>               «
»     load_entry_point('iris', 'console_scripts', 'iris')()                                                            «
»   File "c:\github\iris\iris\__main__.py", line 46, in main                                                           «
»     Iris()                                                                                                           «
»   File "c:\github\iris\iris\__main__.py", line 59, in __init__                                                       «
»     run(self)                                                                                                        «
»   File "c:\github\iris\iris\test_runner.py", line 75, in run                                                         «
»     current.run()                                                                                                    «
»   File "c:\github\iris\iris\tests\experiments\empty.py", line 22, in run                                             «
»     assert_true(self, False, 'test')                                                                                 «
»   File "c:\github\iris\iris\asserts.py", line 60, in assert_true                                                     «
»     assert_equal(test_case, actual, True, message)                                                                   «
»   File "c:\github\iris\iris\asserts.py", line 32, in assert_equal                                                    «
»     test_case.add_results('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))) «
------------------------------------------------------------------------------------------------------------------------

2018-11-02 16:59:15,098 [INFO] [iris.api.helpers.results] [empty] - >>> FAILED <<< (Finished in 13.01 second(s))

2018-11-02 16:59:15,115 [INFO] [iris.test_runner] 
------------------------------------------------------------------------------------------------------------------------
2018-11-02 16:59:15,121 [INFO] [iris.test_runner] Executing: 2 - [clear_all_history]: Clear all the History.
2018-11-02 16:59:37,569 [WARNING] [iris.api.helpers.results] Step: Mozilla page loaded successfully., outcome: >>> FAILED <<< 

------------------------------------------------------------------------------------------------------------------------
» Traceback (most recent call last):                                                                                   «
»   File "C:\Users\paul.silaghi\.virtualenvs\iris-DBojdd3p\Scripts\iris-script.py", line 11, in <module>               «
»     load_entry_point('iris', 'console_scripts', 'iris')()                                                            «
»   File "c:\github\iris\iris\__main__.py", line 46, in main                                                           «
»     Iris()                                                                                                           «
»   File "c:\github\iris\iris\__main__.py", line 59, in __init__                                                       «
»     run(self)                                                                                                        «
»   File "c:\github\iris\iris\test_runner.py", line 75, in run                                                         «
»     current.run()                                                                                                    «
»   File "c:\github\iris\iris\tests\history\clear_all_history.py", line 28, in run                                     «
»     assert_true(self, expected_1, 'Mozilla page loaded successfully.')                                               «
»   File "c:\github\iris\iris\asserts.py", line 60, in assert_true                                                     «
»     assert_equal(test_case, actual, True, message)                                                                   «
»   File "c:\github\iris\iris\asserts.py", line 32, in assert_equal                                                    «
»     test_case.add_results('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))) «
------------------------------------------------------------------------------------------------------------------------

2018-11-02 16:59:37,615 [INFO] [iris.api.helpers.results] [clear_all_history] - >>> FAILED <<< (Finished in 19.84 second(s))

2018-11-02 16:59:37,625 [INFO] [iris.test_runner] 
------------------------------------------------------------------------------------------------------------------------
2018-11-02 16:59:37,631 [INFO] [iris.test_runner] Executing: 3 - [about_firefox_controls]: This is a test of the 'About Firefox' window controls
2018-11-02 16:59:57,532 [WARNING] [iris.api.helpers.results] Step: 'About Firefox' window was opened successfully., outcome: >>> FAILED <<< 

------------------------------------------------------------------------------------------------------------------------
» Traceback (most recent call last):                                                                                   «
»   File "C:\Users\paul.silaghi\.virtualenvs\iris-DBojdd3p\Scripts\iris-script.py", line 11, in <module>               «
»     load_entry_point('iris', 'console_scripts', 'iris')()                                                            «
»   File "c:\github\iris\iris\__main__.py", line 46, in main                                                           «
»     Iris()                                                                                                           «
»   File "c:\github\iris\iris\__main__.py", line 59, in __init__                                                       «
»     run(self)                                                                                                        «
»   File "c:\github\iris\iris\test_runner.py", line 75, in run                                                         «
»     current.run()                                                                                                    «
»   File "c:\github\iris\iris\tests\toolbars_window_controls\about_firefox_controls.py", line 23, in run               «
»     assert_true(self, expected_1, '\'About Firefox\' window was opened successfully.')                               «
»   File "c:\github\iris\iris\asserts.py", line 60, in assert_true                                                     «
»     assert_equal(test_case, actual, True, message)                                                                   «
»   File "c:\github\iris\iris\asserts.py", line 32, in assert_equal                                                    «
»     test_case.add_results('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))) «
------------------------------------------------------------------------------------------------------------------------

2018-11-02 16:59:57,579 [INFO] [iris.api.helpers.results] [about_firefox_controls] - >>> FAILED <<< (Finished in 17.47 second(s))

2018-11-02 16:59:57,591 [INFO] [iris.test_runner] 
------------------------------------------------------------------------------------------------------------------------
2018-11-02 16:59:57,596 [INFO] [iris.test_runner] Executing: 4 - [browser_control_console]: This is a test case that checks that Browser Control Console work as expected.
2018-11-02 17:00:14,345 [ERROR] [iris.api.helpers.results] Error encountered in test, outcome: >>> ERROR <<< 

-----------------------------------------------------------------------------------------------------------
» Traceback (most recent call last):                                                                      «
»   File "c:\github\iris\iris\test_runner.py", line 75, in run                                            «
»     current.run()                                                                                       «
»   File "c:\github\iris\iris\tests\toolbars_window_controls\browser_control_console.py", line 27, in run «
»     pop_up_region = click_hamburger_menu_option('Web Developer')                                        «
»   File "c:\github\iris\iris\api\helpers\general.py", line 234, in click_hamburger_menu_option           «
»     'Can\'t find the option in the page, aborting test.')                                               «
» APIHelperError: Can't find the option in the page, aborting test.                                       «
-----------------------------------------------------------------------------------------------------------

2018-11-02 17:00:14,381 [INFO] [iris.api.helpers.results] [browser_control_console] - >>> ERROR <<< (Finished in 14.16 second(s))

2018-11-02 17:00:14,392 [INFO] [iris.api.helpers.results] 
------------------------------------------------------------------------------------------------------------------------
Platform: win, Firefox Version: 64.0, Firefox Build: 20181101155334
Passed: 0, Failed: 3, Skipped: 0, Errors: 1 -- Total: 4                                      Total time: 74.73 second(s)

The following tests did not pass:
empty
clear_all_history
about_firefox_controls
browser_control_console


------------------------------------------------------------------------------------------------------------------------

